apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: edgehub-backend
  name: edgehub-backend
spec:
  clusterIP: None
  selector:
    app: edgehub-backend
  type: ClusterIP
status:
  loadBalancer: {}
