apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: edgehub-frontend
  name: edgehub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgehub-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edgehub-frontend
    spec:
      containers:
      - image: frontend
        name: frontend
        resources: {}
status: {}
